{{- if and .Values.volumeSnapshotClass.enabled (.Capabilities.APIVersions.Has "snapshot.storage.k8s.io/v1/VolumeSnapshotClass") }}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Values.volumeSnapshotClass.name }}
  labels:
    {{- include "ankra-cloud-csi.labels" . | nindent 4 }}
  {{- if .Values.volumeSnapshotClass.default }}
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  {{- end }}
driver: csi.ankra.cloud
deletionPolicy: {{ .Values.volumeSnapshotClass.deletionPolicy }}
{{- end }}
