// Command openapigen writes the typed operations of the Ankra Cloud API client (internal/ankraapi/operations_gen.go)
// from the Ankra Cloud OpenAPI document: a type for every component schema, a table of every operation, and one typed
// method per operation named after its operationId. Run it through `make client` or `make sync-client`.
package main

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// initialisms are written in upper case in Go names, as Go style asks.
var initialisms = map[string]string{
	"api": "API", "cidr": "CIDR", "cpu": "CPU", "csrf": "CSRF", "dns": "DNS", "http": "HTTP", "https": "HTTPS", "id": "ID", "ids": "IDs",
	"ip": "IP", "ips": "IPs", "ipv4": "IPv4", "ipv6": "IPv6", "iops": "IOPS", "json": "JSON", "mac": "MAC", "mfa": "MFA", "nat": "NAT",
	"oidc": "OIDC", "sha256": "SHA256", "ssh": "SSH", "tcp": "TCP", "tls": "TLS", "ttl": "TTL", "udp": "UDP", "uri": "URI", "url": "URL",
	"urls": "URLs", "vni": "VNI", "vm": "VM", "vms": "VMs", "ha": "HA",
}

// GoName turns a snake_case, kebab-case or camelCase name into an exported Go name.
func GoName(name string) string {
	var words []string
	current := strings.Builder{}
	flush := func() {
		if current.Len() > 0 {
			words = append(words, current.String())
			current.Reset()
		}
	}
	for index, character := range name {
		switch {
		case character == '_' || character == '-' || character == '.' || character == ' ' || character == '/' || character == '|':
			flush()
		case character >= 'A' && character <= 'Z' && index > 0 && current.Len() > 0 && !isUpper(current.String()):
			flush()
			current.WriteRune(character)
		default:
			current.WriteRune(character)
		}
	}
	flush()
	result := strings.Builder{}
	for _, word := range words {
		lower := strings.ToLower(word)
		if initialism, isInitialism := initialisms[lower]; isInitialism {
			result.WriteString(initialism)
			continue
		}
		result.WriteString(strings.ToUpper(lower[:1]) + lower[1:])
	}
	generated := result.String()
	if generated == "" || (generated[0] >= '0' && generated[0] <= '9') {
		generated = "Value" + generated
	}
	return generated
}

func isUpper(text string) bool {
	return strings.ToUpper(text) == text
}

// generator accumulates the generated declarations.
type generator struct {
	specification *openapi3.T
	types         map[string]string
	typeOrder     []string
	usesTime      bool
}

// Generate returns the gofmt-ed Go source of the named package for the specification.
func Generate(specification []byte, packageName string) ([]byte, error) {
	loader := openapi3.NewLoader()
	document, loadError := loader.LoadFromData(specification)
	if loadError != nil {
		return nil, fmt.Errorf("load the specification: %w", loadError)
	}
	if validationError := document.Validate(context.Background()); validationError != nil {
		return nil, fmt.Errorf("validate the specification: %w", validationError)
	}
	state := &generator{specification: document, types: map[string]string{}}
	componentNames := make([]string, 0, len(document.Components.Schemas))
	for name := range document.Components.Schemas {
		componentNames = append(componentNames, name)
	}
	sort.Strings(componentNames)
	for _, name := range componentNames {
		state.declare(schemaTypeName(name), document.Components.Schemas[name].Value, "the "+name+" schema")
	}
	operations := state.operations()
	var output bytes.Buffer
	output.WriteString("// Code generated by tools/openapigen from the Ankra Cloud OpenAPI document. DO NOT EDIT.\n\npackage " +
		packageName + "\n\n")
	output.WriteString("import (\n\t\"context\"\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"net/url\"\n")
	if state.usesTime {
		output.WriteString("\t\"time\"\n")
	}
	output.WriteString(")\n\n")
	output.WriteString("var (\n\t_ = json.RawMessage(nil)\n\t_ = fmt.Sprint\n\t_ url.Values\n)\n\n")
	output.WriteString(state.operationTable(operations))
	sort.Strings(state.typeOrder)
	for _, name := range state.typeOrder {
		output.WriteString(state.types[name])
	}
	for _, operation := range operations {
		output.WriteString(state.method(operation))
	}
	formatted, formatError := format.Source(output.Bytes())
	if formatError != nil {
		return nil, fmt.Errorf("format the generated client: %w\n%s", formatError, output.String())
	}
	return formatted, nil
}

// declare adds a named type for the schema unless one exists.
func (state *generator) declare(name string, schema *openapi3.Schema, origin string) string {
	if _, exists := state.types[name]; exists {
		return name
	}
	state.types[name] = ""
	state.typeOrder = append(state.typeOrder, name)
	var declaration strings.Builder
	if description := firstSentence(schema.Description); description != "" {
		declaration.WriteString("// " + name + " is " + origin + ": " + description + "\n")
	} else {
		declaration.WriteString("// " + name + " is " + origin + ".\n")
	}
	properties := state.objectProperties(schema)
	if properties == nil {
		declaration.WriteString("type " + name + " = " + state.goType(name, schema, true) + "\n\n")
		state.types[name] = declaration.String()
		return name
	}
	declaration.WriteString("type " + name + " struct {\n")
	for _, property := range properties {
		fieldType := state.fieldType(name, property)
		tag := property.name
		if !property.isRequired {
			tag += ",omitempty"
		}
		if description := firstSentence(property.schema.Description); description != "" {
			declaration.WriteString("\t// " + GoName(property.name) + ": " + description + "\n")
		}
		fmt.Fprintf(&declaration, "\t%s %s `json:%q`\n", GoName(property.name), fieldType, tag)
	}
	declaration.WriteString("}\n\n")
	state.types[name] = declaration.String()
	return name
}

// property is one field of an object schema.
type property struct {
	name       string
	schema     *openapi3.Schema
	reference  string
	isRequired bool
}

// objectProperties returns the fields of an object schema (allOf members merged), or nil when the schema is not a
// plain object with properties.
func (state *generator) objectProperties(schema *openapi3.Schema) []property {
	if schema == nil {
		return nil
	}
	collected := map[string]property{}
	required := map[string]bool{}
	var collect func(current *openapi3.Schema) bool
	collect = func(current *openapi3.Schema) bool {
		if len(current.OneOf) > 0 || len(current.AnyOf) > 0 {
			return false
		}
		for _, member := range current.AllOf {
			if member.Value == nil || !collect(member.Value) {
				return false
			}
		}
		for _, name := range current.Required {
			required[name] = true
		}
		for name, reference := range current.Properties {
			collected[name] = property{name: name, schema: reference.Value, reference: reference.Ref}
		}
		return true
	}
	if !collect(schema) || len(collected) == 0 {
		return nil
	}
	names := make([]string, 0, len(collected))
	for name := range collected {
		names = append(names, name)
	}
	sort.Strings(names)
	properties := make([]property, 0, len(names))
	for _, name := range names {
		field := collected[name]
		field.isRequired = required[name]
		properties = append(properties, field)
	}
	return properties
}

// runtimeNames are declared by the hand-written transport (client.go); a schema with one of these names gets the
// suffix Schema.
var runtimeNames = map[string]bool{"Client": true, "Credential": true, "Option": true, "Error": true, "RawResponse": true, "OperationSpec": true,
	"Operations": true, "OperationIDs": true}

// schemaTypeName is the Go type of a component schema.
func schemaTypeName(componentName string) string {
	name := GoName(componentName)
	if runtimeNames[name] {
		return name + "Schema"
	}
	return name
}

func referenceName(reference string) string {
	return schemaTypeName(reference[strings.LastIndex(reference, "/")+1:])
}

// fieldType is the Go type of an object's field: optional and nullable scalars become pointers.
func (state *generator) fieldType(parent string, field property) string {
	if field.reference != "" {
		named := referenceName(field.reference)
		if !field.isRequired || (field.schema != nil && field.schema.Type.IncludesNull()) {
			if isReferenceType(field.schema) {
				return named
			}
			return "*" + named
		}
		return named
	}
	goType := state.goType(parent+GoName(field.name), field.schema, false)
	isNullable := field.schema != nil && field.schema.Type.IncludesNull()
	if (isNullable || !field.isRequired) && !strings.HasPrefix(goType, "[]") && !strings.HasPrefix(goType, "map[") &&
		goType != "json.RawMessage" && goType != "any" && !strings.HasPrefix(goType, "*") {
		return "*" + goType
	}
	return goType
}

// isReferenceType reports whether a schema's Go type already has a nil value (a slice or a map).
func isReferenceType(schema *openapi3.Schema) bool {
	if schema == nil || schema.Type == nil {
		return false
	}
	return schema.Type.Includes("array") || (schema.Type.Includes("object") && len(schema.Properties) == 0)
}

// goType maps a schema to a Go type; inline objects become named types called name.
func (state *generator) goType(name string, schema *openapi3.Schema, isTopLevel bool) string {
	if schema == nil {
		return "json.RawMessage"
	}
	if nullable := nullableMember(schema); nullable != nil {
		if nullable.Ref != "" {
			return "*" + referenceName(nullable.Ref)
		}
		return "*" + state.goType(name, nullable.Value, false)
	}
	if len(schema.OneOf) > 0 || len(schema.AnyOf) > 0 {
		return "json.RawMessage"
	}
	if len(schema.AllOf) == 1 && schema.AllOf[0].Ref != "" && len(schema.Properties) == 0 {
		return referenceName(schema.AllOf[0].Ref)
	}
	types := schema.Type.Slice()
	var primary string
	for _, candidate := range types {
		if candidate != "null" {
			primary = candidate
		}
	}
	switch primary {
	case "string":
		if schema.Format == "date-time" {
			state.usesTime = true
			return "time.Time"
		}
		return "string"
	case "integer":
		return "int64"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		if schema.Items == nil {
			return "[]json.RawMessage"
		}
		if schema.Items.Ref != "" {
			return "[]" + referenceName(schema.Items.Ref)
		}
		return "[]" + state.goType(name+"Item", schema.Items.Value, false)
	}
	if properties := state.objectProperties(schema); properties != nil {
		if isTopLevel {
			return "struct{}"
		}
		return state.declare(name, schema, "an inline object")
	}
	if schema.AdditionalProperties.Schema != nil {
		value := schema.AdditionalProperties.Schema
		if value.Ref != "" {
			return "map[string]" + referenceName(value.Ref)
		}
		return "map[string]" + state.goType(name+"Value", value.Value, false)
	}
	if primary == "object" {
		return "map[string]any"
	}
	return "json.RawMessage"
}

// nullableMember returns the non-null member of `oneOf: [X, {type: null}]`.
func nullableMember(schema *openapi3.Schema) *openapi3.SchemaRef {
	members := schema.OneOf
	if len(members) == 0 {
		members = schema.AnyOf
	}
	if len(members) != 2 {
		return nil
	}
	for index, member := range members {
		if member.Value != nil && member.Value.Type.Is("null") {
			return members[1-index]
		}
	}
	return nil
}

// firstSentence is the first sentence of a description, on one line, ending with a period.
func firstSentence(text string) string {
	text = strings.Join(strings.Fields(text), " ")
	for offset := 0; ; {
		cut := strings.Index(text[offset:], ". ")
		if cut < 0 {
			break
		}
		end := offset + cut
		if strings.HasSuffix(text[:end], "e.g") || strings.HasSuffix(text[:end], "i.e") {
			offset = end + 2
			continue
		}
		text = text[:end+1]
		break
	}
	if len(text) > 160 {
		text = text[:157] + "..."
	}
	if text != "" && !strings.HasSuffix(text, ".") && !strings.HasSuffix(text, "...") {
		text += "."
	}
	return text
}

// parameter is a path or query parameter of an operation.
type parameter struct {
	name       string
	location   string
	goType     string
	isRequired bool
}

// operation is what the generator needs of one operation.
type operation struct {
	identifier     string
	method         string
	path           string
	summary        string
	tag            string
	security       []string
	parameters     []parameter
	bodyType       string
	bodyMedia      string
	resultType     string
	resultIsRaw    bool
	hasNoContent   bool
	permission     string
	operatorScope  string
	staffRole      string
	credentialRead bool
}

func (state *generator) operations() []operation {
	var operations []operation
	paths := state.specification.Paths.Map()
	pathNames := make([]string, 0, len(paths))
	for path := range paths {
		pathNames = append(pathNames, path)
	}
	sort.Strings(pathNames)
	for _, path := range pathNames {
		item := paths[path]
		methods := make([]string, 0, 5)
		for method := range item.Operations() {
			methods = append(methods, method)
		}
		sort.Strings(methods)
		for _, method := range methods {
			value := item.Operations()[method]
			current := operation{identifier: value.OperationID, method: strings.ToUpper(method), path: path, summary: firstSentence(value.Summary)}
			if len(value.Tags) > 0 {
				current.tag = value.Tags[0]
			}
			current.permission = extension(value, "x-ankra-permission")
			current.operatorScope = extension(value, "x-ankra-operator-scope")
			current.staffRole = extension(value, "x-ankra-staff-role")
			current.credentialRead = extension(value, "x-ankra-credential-read") == "true"
			requirements := state.specification.Security
			if value.Security != nil {
				requirements = *value.Security
			}
			for _, requirement := range requirements {
				names := make([]string, 0, len(requirement))
				for name := range requirement {
					names = append(names, name)
				}
				sort.Strings(names)
				current.security = append(current.security, strings.Join(names, "+"))
			}
			sort.Strings(current.security)
			seen := map[string]bool{}
			for _, reference := range append(append(openapi3.Parameters{}, value.Parameters...), item.Parameters...) {
				if reference.Value == nil || seen[reference.Value.In+reference.Value.Name] || (reference.Value.In != "path" && reference.Value.In != "query") {
					continue
				}
				seen[reference.Value.In+reference.Value.Name] = true
				goType := "string"
				if reference.Value.Schema != nil && reference.Value.Schema.Value != nil {
					switch {
					case reference.Value.Schema.Value.Type.Permits("integer") && !reference.Value.Schema.Value.Type.Permits("string"):
						goType = "int64"
					case reference.Value.Schema.Value.Type.Is("boolean"):
						goType = "bool"
					}
				}
				current.parameters = append(current.parameters, parameter{name: reference.Value.Name, location: reference.Value.In, goType: goType,
					isRequired: reference.Value.Required || reference.Value.In == "path"})
			}
			sort.Slice(current.parameters, func(first int, second int) bool {
				if current.parameters[first].location != current.parameters[second].location {
					return current.parameters[first].location == "path"
				}
				return current.parameters[first].name < current.parameters[second].name
			})
			typeName := GoName(value.OperationID)
			if value.RequestBody != nil && value.RequestBody.Value != nil {
				if media := value.RequestBody.Value.Content.Get("application/json"); media != nil && media.Schema != nil {
					current.bodyMedia = "application/json"
					if media.Schema.Ref != "" {
						current.bodyType = referenceName(media.Schema.Ref)
					} else {
						current.bodyType = state.goType(typeName+"Request", media.Schema.Value, false)
					}
				} else {
					for mediaType := range value.RequestBody.Value.Content {
						current.bodyMedia = mediaType
						current.bodyType = "[]byte"
					}
				}
			}
			state.result(&current, value, typeName)
			operations = append(operations, current)
		}
	}
	sort.Slice(operations, func(first int, second int) bool { return operations[first].identifier < operations[second].identifier })
	return operations
}

// result picks the Go type of the operation's success answer.
func (state *generator) result(current *operation, value *openapi3.Operation, typeName string) {
	statuses := make([]string, 0)
	for status := range value.Responses.Map() {
		if strings.HasPrefix(status, "2") || strings.HasPrefix(status, "3") {
			statuses = append(statuses, status)
		}
	}
	sort.Strings(statuses)
	for _, status := range statuses {
		response := value.Responses.Map()[status].Value
		if response == nil {
			continue
		}
		if media := response.Content.Get("application/json"); media != nil && media.Schema != nil {
			if media.Schema.Ref != "" {
				current.resultType = referenceName(media.Schema.Ref)
			} else {
				current.resultType = state.goType(typeName+"Response", media.Schema.Value, false)
			}
			return
		}
		if len(response.Content) > 0 || strings.HasPrefix(status, "3") {
			current.resultIsRaw = true
			return
		}
	}
	current.hasNoContent = true
}

func extension(value *openapi3.Operation, name string) string {
	extensionValue, isPresent := value.Extensions[name]
	if !isPresent {
		return ""
	}
	return fmt.Sprint(extensionValue)
}

func (state *generator) operationTable(operations []operation) string {
	var table strings.Builder
	table.WriteString("// Operations describes every operation of the API by operationId.\nvar Operations = map[string]OperationSpec{\n")
	for _, current := range operations {
		var pathParameters, queryParameters []string
		for _, parameter := range current.parameters {
			if parameter.location == "path" {
				pathParameters = append(pathParameters, strconv.Quote(parameter.name))
			} else {
				queryParameters = append(queryParameters, strconv.Quote(parameter.name))
			}
		}
		security := make([]string, 0, len(current.security))
		for _, requirement := range current.security {
			security = append(security, strconv.Quote(requirement))
		}
		fmt.Fprintf(&table, "\t%q: {ID: %q, Method: %q, Path: %q, Tag: %q, Summary: %q, Security: []string{%s}, PathParameters: []string{%s}, "+
			"QueryParameters: []string{%s}, BodyMediaType: %q, Permission: %q, OperatorScope: %q, StaffRole: %q, IsCredentialRead: %t},\n",
			current.identifier, current.identifier, current.method, current.path, current.tag, current.summary, strings.Join(security, ", "),
			strings.Join(pathParameters, ", "), strings.Join(queryParameters, ", "), current.bodyMedia, current.permission, current.operatorScope,
			current.staffRole, current.credentialRead)
	}
	table.WriteString("}\n\n")
	return table.String()
}

func (state *generator) method(current operation) string {
	name := GoName(current.identifier)
	var source strings.Builder
	parametersType := ""
	if len(current.parameters) > 0 {
		parametersType = name + "Parameters"
		source.WriteString("// " + parametersType + " are the path and query parameters of " + current.identifier + ".\ntype " + parametersType + " struct {\n")
		for _, parameter := range current.parameters {
			fieldType := parameter.goType
			if !parameter.isRequired {
				fieldType = "*" + fieldType
			}
			fmt.Fprintf(&source, "\t%s %s\n", GoName(parameter.name), fieldType)
		}
		source.WriteString("}\n\n")
	}
	arguments := []string{"ctx context.Context"}
	if parametersType != "" {
		arguments = append(arguments, "parameters "+parametersType)
	}
	if current.bodyType != "" {
		arguments = append(arguments, "body "+current.bodyType)
	}
	returns := "error"
	switch {
	case current.resultIsRaw:
		returns = "(RawResponse, error)"
	case current.resultType != "":
		returns = "(*" + current.resultType + ", error)"
	}
	fmt.Fprintf(&source, "// %s calls %s %s (%s): %s\n", name, current.method, current.path, current.identifier, current.summary)
	fmt.Fprintf(&source, "func (client *Client) %s(%s) %s {\n", name, strings.Join(arguments, ", "), returns)
	source.WriteString("\tpathParameters := map[string]string{}\n\tquery := url.Values{}\n")
	for _, parameter := range current.parameters {
		field := "parameters." + GoName(parameter.name)
		target := "pathParameters[" + strconv.Quote(parameter.name) + "] = "
		if parameter.location == "query" {
			target = "query.Set(" + strconv.Quote(parameter.name) + ", "
		}
		closing := ""
		if parameter.location == "query" {
			closing = ")"
		}
		if parameter.isRequired {
			fmt.Fprintf(&source, "\t%sfmt.Sprint(%s)%s\n", target, field, closing)
		} else {
			fmt.Fprintf(&source, "\tif %s != nil {\n\t\t%sfmt.Sprint(*%s)%s\n\t}\n", field, target, field, closing)
		}
	}
	bodyArgument := "nil"
	if current.bodyType != "" {
		bodyArgument = "body"
	}
	call := fmt.Sprintf("client.send(ctx, Operations[%q], pathParameters, query, %s)", current.identifier, bodyArgument)
	switch {
	case current.resultIsRaw:
		source.WriteString("\treturn " + call + "\n")
	case current.resultType != "":
		fmt.Fprintf(&source, "\tvar result %s\n\tif callError := client.decode(ctx, Operations[%q], pathParameters, query, %s, &result); callError != nil {\n\t\treturn nil, callError\n\t}\n\treturn &result, nil\n",
			current.resultType, current.identifier, bodyArgument)
	default:
		fmt.Fprintf(&source, "\t_, callError := %s\n\treturn callError\n", call)
	}
	source.WriteString("}\n\n")
	return source.String()
}
